# Generated by Django 3.2.5 on 2021-07-07 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('idTipo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombreTipo', models.CharField(max_length=50, verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'tipo',
                'verbose_name_plural': 'tipos',
                'ordering': ['nombreTipo'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('precio', models.IntegerField(verbose_name='Precio Unitario')),
                ('marca', models.IntegerField(verbose_name='Marca')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Imagen')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asheeme.tipo')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['descripcion'],
            },
        ),
    ]
