# Generated by Django 3.2.5 on 2021-07-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asheeme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='nombreTipo',
            field=models.CharField(max_length=50, verbose_name='tipo'),
        ),
    ]
