# Generated by Django 3.2.5 on 2021-07-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asheeme', '0003_alter_producto_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('idComentario', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('comentario', models.CharField(max_length=100, verbose_name='Comentario')),
            ],
            options={
                'verbose_name': 'comentario',
                'verbose_name_plural': 'comentarios',
                'ordering': ['comentario'],
            },
        ),
    ]
