# Generated by Django 3.2.5 on 2021-07-08 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asheeme', '0004_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['ccomentario'], 'verbose_name': 'comentario', 'verbose_name_plural': 'comentarios'},
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='comentario',
            new_name='ccomentario',
        ),
    ]
