# Generated by Django 3.2.5 on 2021-07-08 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asheeme', '0005_auto_20210708_0320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['comentario'], 'verbose_name': 'comentario', 'verbose_name_plural': 'comentarios'},
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='ccomentario',
            new_name='comentario',
        ),
    ]
